sudo: false
language: scala
scala:
- 2.12.4-bin-typelevel-4
- 2.11.11-bin-typelevel-4
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
script:
- sbt -Dfile.encoding=UTF8 test
after_success:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt ++$TRAVIS_SCALA_VERSION releaseEarly; fi
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - "$HOME/.coursier"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
before_install:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then openssl aes-256-cbc -K $encrypted_d57b5eec735f_key
  -iv $encrypted_d57b5eec735f_iv -in .travis/secrets.tar.enc -out .travis/local.secrets.tar
  -d; tar xv -C .travis -f .travis/local.secrets.tar; fi
env:
  global:
  - secure: kpqVLCzOiwKwRRCHJGMIucMMt+beI8Uhaqp9jYV3gYbGZi86JzkMemVh9Y29mSYz8zkqEtlmEF8FOPrMmz56WvnRm2x3yTaFySMNSGf5Rf+0NWejU/Cs1JOc0bonxBhf+Y8cP3yqNBAcsoatrLsIwZECRax9p0TxMn6+MICjrhtY4RDn9WEdatdpjgsJEzYi2dz8Z2FpM8dFRqBWB2oAOBTW6TvjRPqNJ2+xHH3t7lPyub/WPfug1GDUw9g7roRQuwU7Bq+9OuCozdAs8sbt/z0TqdWz5+d0qe9/gYCn3bp4g7lVB753fRy3a0aOTVFMg0y6SV60u85k3RYx9UpysgAkbqkqixBIVXQL9o4DAKDIeqIQQxWUvL28UpLJ0D6hWmpzyuQIOaK9KmGLOpsHzMxugs1uXHWWphSRhsY9tlHfKmNe3UKPsmD3OkvhFdPOsAM1lWF4U9s0GnVpgsBetbyJhMPCTUHAiPnOvWyjK2wShENYAEFzhCvrt3k2z5qzEA1BWx6HJY2/+Ra2d1FugTKBeSghYC3tOE+Y54eof9xyVEc/AnAIw6uX6GAt3kSCoujETdDg4TWpA+200dNv9jFVHjy4Bjxvulk4hsAblMfwjELYAdOf0NjLDOKzuR3S8/XS5mG1btgiMLUbYkgu4AyPJIKmdKvY5R4ZPJ+QtU4=
  - secure: UCmJ/R5ShE97hYIvsft4/Yh4B8gFKg2dJHvhlRJqb2VMWYFZZNRXiiFmpKUaaqWt0Wh3wstHKXIhTGHroqV9spnvd60EAFSeLZOp4ZaJx1F6ZM8af6jRyB5MHHaQb+50pjzq3ikkkP+fJ97+Ee8tN+o73M+CAHxYngJdzihXtpWNTaCyFHQMu2V38II1MAzvy3TeZt6EypTARQK6z4ZmipcGNF1Himb4cOsH1opoSRk+tFlTNO7lFCg9iz4mdCWspxMA6PCCQ575MouBv4gbwjCUPW825MazPSfEeMkwUfq5gxVCjFkYQIw+nZ3ZXtYs4N7E5HKS+VRUBAZNvs+mWFmGOfE5cHAI3fvUTyEyTMQUWVGjZ/5UHVVcrx1xbSWdTUczfwQvkTDcojTtQ6TOoo9kWJDJe2B/Oroxxgu7SirUNPOnBuC1ZhM3TtxI1Gzow4nHRYidD2kT5qOX/IRLtS4K2Iy2502X+Dn+6edLxb76v+ONOJ2NQd9G7tRsKbM/VIAby2/zQDeZetJ7NzQJLGj5ajagCvidzMiSq4w5PsAfRsUrhVtrhZ3zTKWHO87rShSz5oTMWAS0+RLZ0ra4YcEi8OnM1FUBf/nvZdiJu8X01UlGPHNXp0PkhPN3a1KT0sEPAm0OxTgo78+zosbuxKC+IswuWMeKsDkSRJDIbWQ=
  - secure: dQfZfrC73Oyj+6jEpCpMWIIUsr6Wm7WBLREw1X+nSxA3/ZkIqZ25xIs4kN/o4gv2ay43hwLpDKfeP4dnpSYt7mPu5T2wlP+5Ih1zrZFXJrUD5RkuRzeKHG3S4aKEJcLK85dYCdKLhtJXeaBOeOUTrUcrEXPlbTTW91uWU5ewuTsjmI0TDPesi5YvCB2V0tihyMBmnXzxwZHKnJYVfdGQhPKyMB5JetIW7prvQoJtsK4ViIQJjunlY9wB9ENu92mXYQ8SbMo1gCjT3+XDcrYRgTh56uKx9hzp1o1RvColW2+kWM3OEWScU2Z/GPzDvn37i3e6DVP3SOhS/mAW3I8FyeRpGSRlPbB2RJ+qyc9gBWYgh2L3Y5sNVi7UrOYOjOAA/KWa8XYqVg+iTYjpnzIt1Qj7NdhjVuDpe4MJhz20wNXPyffqsNSrRrc524GebymyKK1Yll1nHDQNfpOaHoWudt4s8AIAkMJFPcGOi5WWZvaW5jQWJrTuX1cMvtx4nX85jhm8piEC0PVhxoB3GaxVWktrB6QVXFueFM7YYhu8PZxOshOFVmPcwD6E3hmspuNB2IIbdBPYlYrLl07hOq+I/+J94Hi+8asnPvujFmKH0lnJZiC0pwfzLAXV+E1b3DcxDw7Uf/x/8tKa0LOVYLYYbI3PRpBvTTrCNKXSq/0asTQ=
